In [21]:
print("Hello World")
print("Hello World")
print("Hello World")
print("Hello World")

Hello World
Hello World
Hello World
Hello World


In [3]:
import pandas as pd
import numpy as nunu
data_set = pd.read_csv("MusicData.csv")
print(data_set)

           ?Format            Metric  Year  Number of Records Value (Actual)
0               CD             Units  1973                  1            NaN
1               CD             Units  1974                  1            NaN
2               CD             Units  1975                  1            NaN
3               CD             Units  1976                  1            NaN
4               CD             Units  1977                  1            NaN
...            ...               ...   ...                ...            ...
3003  Vinyl Single  Value (Adjusted)  2015                  1    6.205390253
3004  Vinyl Single  Value (Adjusted)  2016                  1    5.198931395
3005  Vinyl Single  Value (Adjusted)  2017                  1     6.33967756
3006  Vinyl Single  Value (Adjusted)  2018                  1    5.386196747
3007  Vinyl Single  Value (Adjusted)  2019                  1    6.795945687

[3008 rows x 5 columns]


C:\Users\princ\AppData\Local\Temp\ipykernel_10784\2254308073.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [4]:
independents = data_set[["?Format","Metric","Year","Number of Records"]].values #values is used to convert data into array format 
print(independents)

[['CD' 'Units' 1973 1]
 ['CD' 'Units' 1974 1]
 ['CD' 'Units' 1975 1]
 ...
 ['Vinyl Single' 'Value (Adjusted)' 2017 1]
 ['Vinyl Single' 'Value (Adjusted)' 2018 1]
 ['Vinyl Single' 'Value (Adjusted)' 2019 1]]


In [5]:
dependents = data_set[["Value (Actual)"]].values # values is used to convert data into array format
print(dependents)

[[nan]
 [nan]
 [nan]
 ...
 ['6.33967756']
 ['5.386196747']
 ['6.795945687']]


In [6]:
# Handle Missing Values in independent variable 
import sklearn # sklearn is a python library
from sklearn.impute import SimpleImputer #impute is used to indentify missing values in data set and fill in missing values by mean, median and mode
imputer = SimpleImputer(missing_values=nunu.nan, strategy='mean')  # SimpleImputer is the class of impute
imputer = imputer.fit(independents[:,2:3]) # it takes missing values in rows and columns 
independents[:,2:3 ] = imputer.transform(independents[:,2:3]) #it is used to replace missing values to mean 
print(independents)

[['CD' 'Units' 1973.0 1]
 ['CD' 'Units' 1974.0 1]
 ['CD' 'Units' 1975.0 1]
 ...
 ['Vinyl Single' 'Value (Adjusted)' 2017.0 1]
 ['Vinyl Single' 'Value (Adjusted)' 2018.0 1]
 ['Vinyl Single' 'Value (Adjusted)' 2019.0 1]]


In [7]:
# Catergorical numerical data:(used to convert data into numeric\)
from sklearn.preprocessing import LabelEncoder #LabelEncoder is a class of sklearn.preprocessing
Label_independents = LabelEncoder() 
independents=Label_independents.fit_transform(independents[:,0]) # we convert our categorical data into numeric data
print(independents)

[ 1  1  1 ... 23 23 23]


In [8]:
# Now we convert our NUMERICAL data into Binary format(0,1) using dummy incodings 
from sklearn.preprocessing import OneHotEncoder #OneHotEncoder is a class of sklearn.preprocessing
One_hotencoder = OneHotEncoder()
independents=One_hotencoder.fit_transform(data_set.Metric.values.reshape(-1,1)).toarray()  # we convert our data into dummy incodings 
print(independents)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [9]:
from sklearn.preprocessing import LabelEncoder 
Label_dependents = LabelEncoder()
dependents=Label_dependents.fit_transform(dependents)
print(dependents)

[1138 1138 1138 ...  936  861  941]


c:\Users\princ\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [11]:
One_hotencoder = OneHotEncoder()
dependents=One_hotencoder.fit_transform(data_set.Metric.values.reshape(-1,1)).toarray()  # we convert our data into dummy incodings 
print(dependents)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [13]:
#Split data sets________________________________________________________________

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independents,dependents,test_size=0.2,random_state=0) #0.2 means 20% data used to train and random value cannot generate so we assigin random value is 0 

In [14]:
print(X_train)

[[0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [15]:
print(X_test)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [18]:
print(y_train)

[[0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [17]:
print(y_test)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [19]:
# standard scaler 

from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train) 
X_test = sc_x.transform(X_test)
print(X_train)

[[-0.62252972 -0.74381461  1.32039523]
 [ 1.60634901 -0.74381461 -0.757349  ]
 [ 1.60634901 -0.74381461 -0.757349  ]
 ...
 [-0.62252972  1.34442103 -0.757349  ]
 [-0.62252972 -0.74381461  1.32039523]
 [-0.62252972 -0.74381461  1.32039523]]


In [20]:
print(X_test)

[[-0.62252972  1.34442103 -0.757349  ]
 [ 1.60634901 -0.74381461 -0.757349  ]
 [-0.62252972  1.34442103 -0.757349  ]
 ...
 [-0.62252972  1.34442103 -0.757349  ]
 [-0.62252972 -0.74381461  1.32039523]
 [-0.62252972  1.34442103 -0.757349  ]]


Now Our data set is ready to feed any models
