In [2]:
import numpy as np 
import pandas as pd

C:\Users\princ\AppData\Local\Temp\ipykernel_2392\118197663.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [3]:
data = pd.read_csv("HeartFailure.csv").values
print(data)

[[ 55.   0. 748. ...   1.  88.   0.]
 [ 65.   0.  56. ...   0. 207.   0.]
 [ 45.   0. 582. ...   0. 244.   0.]
 ...
 [ 95.   1. 112. ...   0.  24.   1.]
 [ 65.   1. 160. ...   0.   8.   1.]
 [ 40.   0. 244. ...   0. 174.   0.]]


In [24]:
column_names = ['age', 'creatinine_phosphokinase', 'diabetes', 'ejection_fraction', 'high_blood_pressure', 'platelets', 'serum_sodium', 'sex', 'smoking', 'time','DEATH_EVENT']


In [27]:
data = np.random.rand(5000, 11) 

In [28]:
data_df = pd.DataFrame(data, columns=column_names)

In [37]:
independent = data_df[['age', 'creatinine_phosphokinase', 'diabetes', 'ejection_fraction', 'high_blood_pressure', 'platelets', 'serum_sodium', 'sex', 'smoking', 'time']].values

In [39]:
print(independent)

[[0.18381807 0.74950593 0.53155854 ... 0.0470865  0.61619708 0.72623351]
 [0.93828199 0.34322641 0.90316549 ... 0.9877558  0.21006478 0.96472598]
 [0.32814192 0.73080487 0.84599705 ... 0.79283928 0.58092849 0.62159431]
 ...
 [0.31152603 0.91055396 0.72614601 ... 0.89081342 0.84959756 0.67800436]
 [0.43024277 0.58235    0.67128704 ... 0.89899242 0.67708045 0.79890993]
 [0.1415537  0.45138742 0.77951764 ... 0.74014144 0.64885648 0.3688576 ]]


In [31]:
print(data_df.columns)

Index(['age', 'creatinine_phosphokinase', 'diabetes', 'ejection_fraction',
       'high_blood_pressure', 'platelets', 'serum_sodium', 'sex', 'smoking',
       'time', 'DEATH_EVENT'],
      dtype='object')


In [35]:
dependent = data_df[['DEATH_EVENT']].values

In [36]:
print(dependent)

[[0.05018268]
 [0.53873932]
 [0.82639783]
 ...
 [0.50476145]
 [0.73759121]
 [0.30915675]]


In [40]:
import sklearn
from sklearn.impute import SimpleImputer

In [41]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [42]:
impute=imputer.fit(independent[:,1:10])

In [43]:
independent[:,1:10]=impute.transform(independent[:,1:10])

In [44]:
independent

array([[0.18381807, 0.74950593, 0.53155854, ..., 0.0470865 , 0.61619708,
        0.72623351],
       [0.93828199, 0.34322641, 0.90316549, ..., 0.9877558 , 0.21006478,
        0.96472598],
       [0.32814192, 0.73080487, 0.84599705, ..., 0.79283928, 0.58092849,
        0.62159431],
       ...,
       [0.31152603, 0.91055396, 0.72614601, ..., 0.89081342, 0.84959756,
        0.67800436],
       [0.43024277, 0.58235   , 0.67128704, ..., 0.89899242, 0.67708045,
        0.79890993],
       [0.1415537 , 0.45138742, 0.77951764, ..., 0.74014144, 0.64885648,
        0.3688576 ]])