Essential Libraries And Tools


In [2]:
import numpy as np 
x = np.array([[1,2,3],[4,5,6]])
print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


In [3]:
import scipy 
from scipy import sparse
# Creat a 2D Numpy array with a diagonal of ones, and zeros everywhere
eye = np.eye(4)
print("Numpy array :\n{}".format(eye))

Numpy array :
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
#convert to numpy array to a scipy matrix in CSR format
#Only the non zeros entries are stored in the matrix
