In [4]:
import numpy as np 
x = np.array([2,3,56,67,67])
y = np.array([34,34,56,32,12])
print(x+y)

[ 36  37 112  99  79]


In [30]:
x=[[1,2,3],[3,4,5],[4,6,7]]
y=[[1,2,3],[3,4,5],[4,6,7]]
for i in range (len(x)):
    for j in range (len(y)):
        print(x[i][j] + y[i][j])
        


2
4
6
6
8
10
8
12
14


In [35]:
a = [[1, 2, 3], [3, 4, 5], [4, 5, 6]]
b = [[1, 2, 3], [3, 4, 5], [4, 56, 65]]

k = [[0 for _ in range(len(b[0]))] for _ in range(len(a))]


for i in range(len(a)):
    for j in range(len(b[0])):
        k[i][j] = a[i][j] * b[j][i]
    print(k[i][j],)


12 	
280 	
390 	


# SciPy Sparse Matrix in CSR format

In [38]:
a = np.eye(10)
print("numpy arrays \n{}".format(a))

numpy arrays 
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
